### ISSUE TITLE
Indicating equal contribution

### ISSUE THREAD

**Issue by expectopatronum** [ismir/paper_templates#28]
Hi!
My colleagues and I are currently preparing the camera ready for this year's ISMIR and we are wondering how we could indicate "equal contribution" for the first two authors.

Possible solutions include adding a sentence to the Acknowledgements section, like in [this ISMIR 2020 paper](https://program.ismir2020.net/poster_4-10.html) or adding a dedicated "Author Contributions" section like in [this ISMIR 2021 preprint](https://psyarxiv.com/jsa4u).
Our preferred solution (because it's the most visible one) would be to add it to the author markup, like it is done here in [this ISMIR 2019](https://archives.ismir.net/ismir2019/paper/000054.pdf) paper, which looks like they are using \thanks. For our paper this would look like this:

```
\multauthor
{Verena Praher$^{1*}$ \hspace{1cm} Katharina Prinz$^{1*}$\thanks{* Equal contribution.}  <other authors>}
```

However, the template contains the following comment `% Note: Please do NOT use \thanks or a \footnote in any of the author markup`. 

Is it ok to use the `\thanks` command for this purpose? Or is there another suggested solution to indicate shared authorship in an ISMIR publication?

Thanks a lot and best regards
Verena & Katharina

**Comment by stefan-balke** [comment]
Hey Verena & Katharina,

good questions, I don't think there is any best practice yet.
You should reach out to the publication chairs:
ismir2021-papers@ismir.net

My 2 cents:
If the "thanks" markup works, use that since it show the information closest to the "source".
The note in the template is more for the case that people use thanks to show affiliations which is not the intended use in the ISMIR template!

Let us know what they say.
Maybe we should then add it to the template.

Best
Stefan

**Comment by expectopatronum** [comment]
Hi Stefan,
thanks for your response! The chairs told us that it is ok to use the \thanks command.

Best regards
Verena
