### ISSUE TITLE
\DocumentMetadata{testphase={phase-III,math}} makes error 

### ISSUE THREAD

**Issue by jdasam** [ismir/paper_templates#44]
Hi! I found that the v2 template for camera-ready makes an error in (at least) Overleaf.

`Package tagpdf Error: The number of automatic begin (53) and end (52)`
`(tagpdf)    text-unit para hooks differ! For immediate help type H <return>. ... l.264 \end{document}`

If I comment out the first line, `\DocumentMetadata{testphase={phase-III,math}}`, the compile works without error even though I don't know how to check whether the alt text is working properly. 

You can check it on the link below
https://www.overleaf.com/read/wzkrdvjfhhsw#8a3794 

Although the Overleaf compile works fine with this error, users cannot run "Submission" to arXiv or any other format on Overleaf because of this error.

I would appreciate a lot if someone can handle this issue!

**Comment by cwu307** [comment]
Hello! Thanks for flagging this! This issue was addressed in a recent PR and should have been fixed in the latest release (v3). Please pull the latest version and let us know if you still encounter issues. 

Thanks!

For more context, you could refer to this PR:
https://github.com/ismir/paper_templates/pull/43

@MCMcCallum FYI

**Comment by jdasam** [comment]
Thank you for the fast reply! I thought that recent PR only handled issues on LBD template so I didn't check it carefully. 

Sure, the problem is solved with v3. Thank you!
